- PagarMe.Shared/Transaction.cs
- PagarMe/PagarMe.sln
> Transaction: add CardCvv property

- PagarMe.Shared/Transaction.cs
> Fix Transaction NSU wrong type.

- PagarMe.Pcl.nuspec
- PagarMe.Shared/Transaction.cs
- PagarMe.Tests/TransactionTests.cs
- PagarMe.nuspec
Meant to be used by the partial refund feature.
> Add amount parameter to Refund method on Transaction

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
If approved this PR will change Nuget Package Version from 2.5 to 2.6.
> Bump Version to 2.6.0

- PagarMe.Shared/Model/Item.cs
If approved, this PR will add Attributes Venue and Date to Model Item.
> Add Venue and Date attribute to Model Item

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
If approved this PR will change version of Nuget Package to 2.6.1
> Bump Version to 2.6.1

- PagarMe.Shared/Model/Transaction.cs
> change Tid and Nsu type from int to string

- PagarMe.Shared/Model/Recipient.cs
Add automatic_anticipation_delay, automatic_anticipation_days and automatic_anticipation_type params to model Recipient.
> Add missing parameters for model Recipient

- PagarMe.Pcl.nuspec
- PagarMe.Shared/Model/Recipient.cs
- PagarMe.nuspec
If approved This PR Will fix field AutomaticAnticipation1025Delay previously named AutomaticAnticipationDelay
> Fix Field AutomaticAnticipationDelay wrongly named

- PagarMe.Shared/Model/Recipient.cs
If approved thir PR  will add status and status_reason to model Recipient
> Add Parameter status and status_reason to model Recipient

- PagarMe.Shared/Model/Transaction.cs
- PagarMe.Tests/TransactionTests.cs
If approved this PR will add refuse reason to Transaction Model.
> Add Refuse Reason to Transaction Model

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
If approved this PR will bump nuget package version to 2.6.7
> Change version to 2.6.7

- PagarMe.Shared/Model/Transaction.cs
- PagarMe.Tests/TransactionTests.cs
If approved this PR will add Refund With Split Method.
> Add Refund With Split Method

- PagarMe.Pcl.nuspec
- PagarMe.Shared/Enumeration/TransactionStatus.cs
- PagarMe.nuspec
If approved thir PR will add Transaction Model missing statuses.
> Add missing status to model transaction

- PagarMe.Pcl.nuspec
- PagarMe.Shared/Model/Transaction.cs
- PagarMe.nuspec
If approved this PR will add subscription_id parameter to model Transaction
> Add subscription_id parameter to model Transaction

- PagarMe.Shared/Model/Subscription.cs
Add amount to allow Subscriptions to be created with Pinpad.
> Add amount to subscription model

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
> Bump version to 2.6.10

- PagarMe.Shared/PagarMeRequest.cs
Add handle to application config
> Add application config handle

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
> Bump Version to 2.6.11

- PagarMe.Pcl.nuspec
- PagarMe.Shared/PagarMeRequest.cs
- PagarMe.nuspec
Adiciona os headers `X-PagarMe-User-Agent` nas requisições.
Isso nos permitirá colher métricas através de logs e do banco de dados
> add X-PagarMe-User-Agent to requests

- PagarMe.Shared/Model/Subscription.cs
- PagarMe.Tests/PagarMeTestFixture.cs
- PagarMe.Tests/SubscriptionTests.cs
pagarme-net: Add feature settle charges in subscription    
Resolves: #75
See also: #73
pagarme-net : Add test for settle charges feature
See also: #73, #75
> Feature/settle charges#2

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
> Bump to version 2.6.13

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
> Bump to version 2.6.14

- PagarMe.Shared/Enumeration/TransactionStatus.cs
- PagarMe.Shared/Model/SplitRule.cs
Fix null parameters from Split Rule and Add Analyzing status to Model Transaction
> Fix some parameters from Split Rule and Add Analyzing status

- PagarMe.Shared/Model/PixAditionalField.cs
- PagarMe.Shared/Model/Transaction.cs
- PagarMe.Shared/PagarMe.Shared.projitems
Adição da forma de pagamento Pix, os campos de requisição e campo de resposta.
> Add pix payment_method and pix fields

- PagarMe.Shared/Model/Transaction.cs
- PagarMe.Shared/PagarMeRequest.cs
- PagarMe.Shared/PagarMeService.cs
Add Header X-PagarMe-Version
Add Reference Key Parameter
> Add Header Version and Reference Key

- PagarMe.Pcl.nuspec
- PagarMe.nuspec
> bump: add new version

- PagarMe.Shared/Enumeration/DocumentType.cs
Add DocumentType passport to Enum.
> Add documentType Passport to enum

- PagarMe.Net40/PagarMe.Net40.csproj
- PagarMe.Pcl.nuspec
- PagarMe.nuspec
Muda a versão do pacote pela definição realizada. 
Adiciona o NETFRAMEWORK Profile para adequar o funcionamento na versão 4.0 do .NET Framework
> Add TargetVersion to CSProj and Bump version to 2.7.2

- PagarMe.Shared/Model/BoletoFine.cs
- PagarMe.Shared/Model/BoletoInterest.cs
- PagarMe.nuspec
PR para corrigir o namespace que subiu na ultima alteração.
> update namespace and version nuspec

- PagarMe.Shared/Model/Payable.cs
- PagarMe.Tests/PayableTest.cs
Objetivo da PR é ajustar o tipo do `transactionId` para `long`.
> fix: change type transactionId to long
